### ISSUE TITLE
adjust to DST

### ISSUE THREAD

**Issue by bkbartk** [guino/BazzDoorbell#99]
Hello,

does anyone know how to adjust the timestamp in the video to DST?
6 months back, I remember after a lot of trying I was able to adjust this,
but I forgot, and didn't document.

**Comment by bkbartk** [comment]
ok, found something,
If I disable offline.sh and also all other blocking.
the file
`/home/cfg/TZ`
changes from
`CST-1:00:00`
to
`CST-2:00:00`

and that's it,
only when changing this manual I need to apply a reboot.
would there be a way to do this without any reboot?

**Comment by guino** [comment]
@bkbartk when using the camera online the tuya servers adjust the time automatically. When using the device offline you may need to adjust the time on your ntp server or device (as you pointed out) -- since that timezone file is likely only read when starting the main application you will need to either reboot or kill ppsapp and run it again.

**Comment by bkbartk** [comment]
Thank you,
Killing PPSAPP reboots my camera as well, so reboot it is.
I will try to create some Home assistant automation to automatically apply DST.
